/*
 MONK LOVES CYCLING. HE WANTS TO BUY HIS FAVORITE BICYCLE COSTING p DOLLARS . 
 BUT HIS FATHER WON'T GIVE HIM TEH MONEY SO EASILY SA HE WANTS MONK TO UNDERSTAND 
 THE IMPORTANCE OF MONEY .ON EACH DAY MONK WILL GO TO ANOTHER CITY WHERE GOD OF 
 MONEY LIVES AND WILL GET AS MUCH AS DOLLARS HE WANTS FROM HIM

 AT THE END OF THE EACH DAY MONK BRINGS THE PIGGY BANK TO HIS FATHER WHO COUNTS
 THE MONEY IN THE PIGGYBANK AND DEPOSISTS AS MUCH MORE MONEY AS THE AMOUNT THAT IS P
 PRESENT IN THE PIGGYBANK KEEPS GROWING.
 MONK WANTS TO ASK GOD OF MONEY FOR AS MINIMUM DOLLARS AS POSSIBLE . FIND THE MINIMUM 
 DOLLARS THAT MONK HAS TO ASK FROM GOD OF MONEY SO THAT HE HAS EXACTLY p DOLLARS IN 
 HIS PIGGYBANK IRRESPONSIBLE OF THE NUMBER OF DAYS HE TAKES
*/

// #include<bits/stdc++.h>
#include<iostream>
using namespace std;

// int  

int main(){

	#ifndef ONLINE_JUDGE
		freopen("input.txt","r",stdin);
		freopen("output.txt","w",stdout);
	#endif

	int t;
	cin>>t;
	while(t--){
		long long x;
		cin>>x;
		cout<< __builtin_popcountll(x)<<"\n";

	}	

	return 0;  
}